# This file was generated by GoReleaser. DO NOT EDIT.
class Ory < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/ory/ory/releases/download/v0.0.18/ory_0.0.18_macOS_64-bit.tar.gz"
  version "0.0.18"
  sha256 "b661da35ddc8024e6e415bb80e06aae72f46f2d7a3c1928e883e85d302490ce7"

  def install
    bin.install "ory"
  end
end
