# This file was generated by GoReleaser. DO NOT EDIT.
class Ory < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/ory/ory/releases/download/v0.0.17/ory_0.0.17_macOS_64-bit.tar.gz"
  version "0.0.17"
  sha256 "d7ffbfc308b196e97bf3ee436cebae6ec4478b0e8a1fdb3a3183d393f5d253bf"

  def install
    bin.install "ory"
  end
end
