# This file was generated by GoReleaser. DO NOT EDIT.
class Ory < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/ory/ory/releases/download/v0.0.16/ory_0.0.16_macOS_64-bit.tar.gz"
  version "0.0.16"
  sha256 "261fc2194e358c0edf4ec4656ce2e3f6359567619d9f6ef42832871fb7968cd1"

  def install
    bin.install "ory"
  end
end
