# This file was generated by GoReleaser. DO NOT EDIT.
class Ory < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/ory/ory/releases/download/v0.0.10/ory_0.0.10_macOS_64-bit.tar.gz"
  version "0.0.10"
  sha256 "68d0accb55624e5584ef677bdb32c8a647fea77978b9f03d782b099d4c6f203c"

  def install
    bin.install "ory"
  end
end
